fileupload/urls.py
from django.conf.urls.defaults import *
from views import UserFileCreateView, UserFileDeleteView, UserFileListView

urlpatterns = patterns('',
    (r'^new/$', UserFileCreateView.as_view(), {}, 'upload-new'),
    (r'^delete/(?P<slug>.+)$', UserFileDeleteView.as_view(), {}, 'upload-delete'),
    (r'^list/(?P<file_type>.+)$', UserFileListView.as_view(), {}, 'upload-list'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings			  
from django.views.generic.simple import direct_to_template 

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from tastypie.api import Api
from api import *

from guides.views import *


v1_api = Api(api_name='v1')
v1_api.register(UserResource())

v1_api.register(MediaElementResource())
v1_api.register(ActionResource())
v1_api.register(InputElementResource())
v1_api.register(MapPointElementResource())
v1_api.register(CardResource())
v1_api.register(ImageResource())
v1_api.register(UserFileResource())
v1_api.register(SmallCardResource())
v1_api.register(GuideResource())
v1_api.register(SmallGuideResource())
v1_api.register(FullGuideResource())
v1_api.register(TheFResource())




urlpatterns = patterns('',
    # Examples:
    # (r'^$', ListView.as_view(model=Guide)),

    (r'^$', Landing),
    (r'^home/$', Home),
    (r'^enjoy/$', GuidesList),

    url(r'^g/(?P<slug>[^/]+)/?$', GuideDetailView, name='GuideDetailView'),
    url(r'^g/(?P<gslug>[^/]+)/(?P<slug>[^/]+)/?$', CardInStack,  name='CardInStackView'),
    url(r'^shhh/(?P<private_url>[^/]+)/?$', SecretGuideView,  name='SecretGuideView'),
    url(r'^shhh/(?P<private_url>[^/]+)/(?P<slug>[^/]+)/?$', SecretCardView,  name='SecretCardView'),
    # url(r'^s/(?P<gslug>[^/]+)/?$', CardInStack),
    # url(r'^g/(?P<gslug>[^/]+)/(?P<slug>[^/]+)/?$', CardDetailView, name='CardDetailView'),
    url(r'^i/(?P<id>[^/]+)/?$', CardDetailViewByIdRedirect, name='CardDetailViewByIdRedirect'),
	
	
	url(r'create/?$', CreateGuide, name='CreateGuide'),
	url(r'create/(?P<gslug>[^/]+)/?$', EditGuide, name='EditGuide'),
	url(r'create/publish/(?P<gslug>[^/]+)/?$', PublishGuide, name='PublishGuide'),
	url(r'create/(?P<gslug>[^/]+)/add/?$', BuildCard, name='BuildCard'),
	url(r'create/(?P<gslug>[^/]+)/addfloating/?$', BuildFloatingCard, name='BuildFloatingCard'),
	url(r'create/(?P<gslug>[^/]+)/(?P<id>[^/]+)/?$', EditCard, name='EditCard'),
	url(r'^upload/', include('fileupload.urls')),
	(r'^api/', include(v1_api.urls)),

	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),		  
	url(r'^accounts/', include('invitation.urls')),
	url(r'^accounts/', include('registration.backends.default.urls')), 
	url(r'^accounts/', include('registration.urls')),				
	url(r'^accounts/', include('registration.auth_urls')),        
	url(r'^accounts/', include('accounts.urls')),	    
	url(r'^user/', include('accounts.urls')),  
	
	url(r'^tagging_autocomplete/', include('tagging_autocomplete.urls')),

	# url(r'^photologue/', include('photologue.urls')),

)


urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
			'document_root': settings.MEDIA_ROOT,
		}),
   )

fileupload/models.py
from django.db import models
import datetime 
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from django.conf import settings

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from imagekit.models import ImageModel
from django.db.models.signals import post_save, pre_save


SELEMENT_TYPE = (
	('image', 'Image'),
	('audio', 'Audio'),
	('video', 'Video'),
	('other', 'Other'),
)

class Image(ImageModel):
	original_image = models.ImageField(upload_to='uimages')
	class IKOptions:
		spec_module = 'fileupload.specs'
		cache_dir = 'userimagecache'
		image_field = 'original_image'
	def __unicode__(self):
		return self.original_image.name
		
class UserFile(models.Model):
	file = models.FileField(upload_to='userfiles', blank=True, null=True)
	slug = models.SlugField(max_length=150, blank=True)
	created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
	owner = models.ForeignKey(User, blank=True, null=True)
	type = models.CharField(blank=True, max_length=5, choices = SELEMENT_TYPE)
	image = models.ForeignKey(Image, blank=True, null=True)
	thumb_url = models.URLField(blank=True)
	medium_url = models.URLField(blank=True)
	display_url = models.URLField(blank=True)
	class Meta:
		ordering = ['-created']
	# content_type = models.ForeignKey(ContentType)


	def __unicode__(self):
		return self.file.name

	@property
	def url(self):
		return (settings.MEDIA_URL + self.file.name) #removed string /media/ and changed slug to file





def resize_images(sender, instance=None, **kwargs):
	if instance.image:	
		instance.thumb_url = instance.image.thumbnail_image.url
		instance.medium_url = instance.image.medium_image.url
		instance.display_url = instance.image.display_image.url




pre_save.connect(resize_images, sender=UserFile)

guides/models.py
from django.db import models
import datetime 
import tagging
from tagging.fields import TagField
from django.contrib.auth.models import User
# from model_utils.managers import InheritanceManager
from django.template.defaultfilters import slugify
from autoslug import AutoSlugField
from django.conf import settings

from django.core import serializers


import jsonfield 

from fileupload.models import UserFile

from log import getlogger
logger=getlogger()
# logger.info("-------z--------")


SELEMENT_TYPE = (
	('image', 'Image'),
	('audio', 'Audio'),
	('video', 'Video'),
	('other', 'Other'),
)

IELEMENT_TYPE = (
	('button', 'Button'),
	('M', 'Multiple Choice'),
	('Y', 'Yes/No'),
	('V', 'Enter Value'),
	('N', 'Enter Numerical Value'),
	('S', 'Sensor'),
	('timer', 'Timer'),
	('place', 'Place'),
)

class Theme (models.Model):
	name = models.CharField(max_length=512)
	text = models.TextField(blank=True, null=True)
	owner = models.ForeignKey(User)
	is_public = models.BooleanField(default=True)
	def __unicode__(self):
		return self.name

class Guide (models.Model):
	title = models.CharField(max_length=500)
	slug = AutoSlugField(populate_from='title', unique=True)
	description = models.TextField(blank=True)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	is_linear = models.BooleanField(default=True) #if true, we should auto add next and back buttons
	enable_comments = models.BooleanField(default=True)
	text_slugs_for_cards = models.BooleanField(default=True)
	tags = TagField()

	cards = models.ManyToManyField('Card', blank=True, null=True, related_name="cards_in_guide")
	card_order =jsonfield.JSONField(default="[]", blank=True) 
	floating_list =jsonfield.JSONField(default="[]", blank=True) 
	theme = models.ForeignKey(Theme, blank=True, null=True)
	owner = models.ForeignKey(User, blank=True, null=True)
	
	show_toc = models.BooleanField(default=False)
	first_card = models.ForeignKey('Card', blank=True, null=True, related_name="+")
	published = models.BooleanField(default=False)
	private = models.BooleanField(default=False)
	private_url = models.CharField(max_length=40, blank=True, null=True) #500 on server
	thumb = models.ForeignKey(UserFile, null=True, blank=True)
	
	submit_to_cat = models.BooleanField(default=True) #new to server
	accepted_to_cat = models.BooleanField(default=False) #new to server
	
	def save(self, *args, **kwargs):
		i=0
		thumb= self.thumb
		if self.is_linear:
			for c in self.card_order: #ugly
				i+=1
				card=Card.objects.get(pk=c)
				if i==1 and not self.show_toc:
					self.first_card = card #set first card to (you guessed it)			
				card.card_number = i
				card.is_floating_card= False
				card.saved_by_guide()
				if not thumb:
					images = card.mediaelement_set.filter(type='image')
					if len(images):
						if not images[0].external_file:
							self.thumb= images[0].file
					
		j=0
		for c in self.floating_list:
			j+=1
			card=Card.objects.get(pk=c)
			if not self.first_card and j==1 and not self.show_toc:
				self.first_card = card	
			card.is_floating_card= True
			card.card_number= 0
			card.saved_by_guide()
			if not thumb:
				images = card.mediaelement_set.filter(type='image')
				if len(images):
					if not images[0].external_file:
						self.thumb= images[0].file
		super(Guide, self).save(*args, **kwargs)
	
	def __unicode__(self):
		return self.title
		
	class Meta:
		ordering = ['-created']
		
	@models.permalink
	def get_absolute_url(self):
		return ('GuideDetailView', (), {'slug': self.slug })
		
	def get_prev_card(self, card):
		prev_card_number = card.card_number -2 # 2 because the list card_order is zero based
		if prev_card_number >=0:
			return Card.objects.get(pk=(self.card_order[prev_card_number]))
		else: 
			return None

	def get_next_card(self, card):
		next_card_number = card.card_number  #no +1 because card_order is 0 based
		if not next_card_number >= len(self.card_order):
			return Card.objects.get(pk=(self.card_order[next_card_number]))
		else: 
			return None
			
	def get_guide_thumb(self):
		if self.thumb:
			return self.thumb.thumb_url

	@property
	def resource_uri(self):
		g = GuideResource() #  is imported at the end of this file
		return g.get_resource_uri(self)


class Card (models.Model):
	title = models.CharField(max_length=500, blank=True, null=True, default="")
	created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
	modified = models.DateTimeField(auto_now=True, blank=True, null=True) #TODO ADD BACK IN
	slug = AutoSlugField(unique_with='guide__slug', populate_from=lambda instance: instance.title or 'card-'+str(instance.card_number) or 'sidecard')
	text = models.TextField(blank=True, null=True)
	guide= models.ForeignKey(Guide, null=True) #we'll use this as the default guide..., otherwise theres no absolute url
	tags = TagField()
	card_number = models.IntegerField(blank=True, null=True) #for default guide.  1 based (not 0)
	primary_media = models.ForeignKey('MediaElement', blank=True, null=True, related_name='primary_media', default=None,  on_delete=models.SET_DEFAULT)
	is_floating_card = models.BooleanField(default=False)
	theme = models.ForeignKey(Theme, blank=True, null=True)
	owner = models.ForeignKey(User, blank=True, null=True)
	autoplay = models.BooleanField(default=False)
	primary_is_bg = models.BooleanField(default=False)
	has_lots_of_text = models.BooleanField(default=False)
	show_next = models.BooleanField(default=True)
	show_prev = models.BooleanField(default=True)
	give_images_shadows = models.BooleanField(default=False)
	children = models.ManyToManyField('self', blank=True, null=True, related_name="children")
	
	def __unicode__(self):
		if self.title !="":
			return self.title
		else:
			if not self.is_floating_card:
				return "Untitled Card #" + str(self.card_number)
			else: 
				return "Untitled Floating Card"
				

	@models.permalink # comment this out if using the hash...
	def get_absolute_url(self):
		# return '/s/' + self.guide.slug +"/#" + self.slug
		return ('CardInStackView', (), {'gslug': self.guide.slug, 'slug':self.slug })
				
	def firstsave(self, *args, **kwargs):
		self.owner= self.guide.owner
		if self.guide.is_linear:
			number_of_cards = len(self.guide.card_order)
			if not self.is_floating_card:
				self.card_number = number_of_cards
			super(Card, self).save(*args, **kwargs)
			if not self.is_floating_card:
				self.guide.card_order.append(self.id)
			else:
				self.guide.floating_list.append(self.id)
			self.guide.cards.add(self)
			self.guide.save()
		else:
			super(Card, self).save(*args, **kwargs)
			self.guide.floating_list.append(self.id)
			self.guide.cards.add(self)
			self.guide.save()



	def saved_by_guide(self, *args, **kwargs):
		super(Card, self).save(*args, **kwargs)
		
	#when the guide is saving the cards, it deals with the ordering.
	def save(self, *args, **kwargs):
		self.brand_new = False
		if self.title:
			if unicode.isalpha(self.title[0]):
				self.slug=slugify(self.title)
			else:
				self.slug = 'c'+ slugify(self.title) #later, we'll use the slug as the DOM id of the card
		else:
			self.slug=None
			
		if self.id:
			self.id=int(self.id) #quotes were messing up guide.card_order
		else: #if it doesn't have an id, just save the damn thing
			self.firstsave(*args, **kwargs)

		if self.is_floating_card:
			if self.id in self.guide.card_order: 
				# logger.info("switched from ordered to floating- saved")
				self.guide.card_order.remove(self.id)
				self.guide.floating_list.append(self.id)
				self.card_number = None
				self.guide.save()
			else:
				pass #it is floating, it was floating, it remains floating
		else: 
			if self.id in self.guide.card_order:
				pass
				# logger.info("saved an ordered card, it was already ordered")
			else:
				# logger.info("was unordered, now it is, adding it to order as last card")
				number_of_cards = len(self.guide.card_order)
				self.card_number = number_of_cards +1
				self.guide.card_order.append(self.id)
				self.guide.save()
				
		# If they didn't select a primary, give it one
		if not self.primary_media:
			images = self.mediaelement_set.filter(type='image')
			if len(images):
				self.primary_media = images[0]
			#defaults to video
			videos = self.mediaelement_set.filter(type='video')
			if len(videos):
				self.primary_media = videos[0]
				
		
		super(Card, self).save(*args, **kwargs)

	
	def delete(self, *args, **kwargs):
		if self.id in self.guide.card_order:
			self.guide.card_order.remove(self.id)
			self.guide.save()
		if self.id in self.guide.floating_list:
			self.guide.floating_list.remove(self.id)
			self.guide.save()
		super(Card, self).delete(*args, **kwargs)

	
	class Meta:
		ordering = ['is_floating_card','card_number'] 

	@property
	def resource_uri(self):
		r = CardResource() # cardresource is imported at the end of this file
		return r.get_resource_uri(self)
		
	def the_audio(self):
		return self.mediaelement_set.filter(type='audio')

	def the_video(self):
		return self.mediaelement_set.filter(type='video')
		
	def has_thumbs(self):
		count = len(self.mediaelement_set.filter(type='image'))
		count+= len(self.mediaelement_set.filter(type='video'))
		count+= len(self.mediaelement_set.filter(type='other'))
		if count > 1:
			return True
		else:
			return False
	
	@property
	def has_map(self):
		count = len(self.inputelement_set.filter(type='place'))
		
		if count:
			return True
		else:
			return False
		
	def cget_prev_card(self):
		prev_card_number = self.card_number -2 # 2 because the list card_order is zero based
		if prev_card_number >=0:
			return Card.objects.get(pk=(self.guide.card_order[prev_card_number]))
		else: 
			return None

	def cget_next_card(self):
		next_card_number = self.card_number  #no +1 because card_order is 0 based
		if not next_card_number >= len(self.guide.card_order):
			return Card.objects.get(pk=(self.guide.card_order[next_card_number]))
		else: 
			return None
			
	def get_thumb(self):
		if self.primary_media:

templates/create/edit_guide.html
{%extends "base.html" %}

{%block title%} Edit Guide {%endblock%}

{%block extrahead%}
	<script src="{{STATIC_URL}}create-guide.js"></script>
	
	<script type="text/javascript">
		var guide_json = '{{guide_json|safe|escapejs}}'; 
		var tag_api_url = "{%url tagging_autocomplete-list%}";		
		
	</script>

{%endblock%}

{%block header%}
	<li><span class="location"> Editing Guide</span></li>
	<li><a href="#publish"> Publish <i>{{guide.title|title}}</i></a>
{%endblock%}

{% block content %} 
<h1>{{guide.title}}</h1>
<h3 class="centext">{{guide.description}}</h3>
<br><br>

{%if guide.is_linear %}
	<div class="row">
		<div class="span10 columns"><h2>Cards</h2> </div>
		<div class="span6 columns"><h2> Side Cards</h2> </div>
	</div>
	
	<div class="row">
		<div class="normal_card_container connectedSortable span10 columns" data-bind="template: {name: 'smallCardTemplate',
						  						foreach: VM.normal_cards, templateOptions: { parentList: VM.normal_cards}},
						 						sortableList: VM.normal_cards">
				
				<div class="cf"></div>
				<p>These are normal cards, so your users can move between them easily, in this order.</p><p> You can reorder these cards by <strong>dragging and dropping</strong> them. Drag one over to the side card section to take it out of the order.</p>		

		</div>
		
		<div class="floating_card_container span6 columns" >
			<div data-bind="template: {name: 'smallCardTemplate',
						  						foreach: VM.floating_cards, templateOptions: { parentList: VM.floating_cards}},
												sortableList: VM.floating_cards" class="connectedSortable ">
			</div>									
			<div class="cf"></div>
			<p><strong>Side cards</strong> are outside the normal flow of your guide. Mostly, this means they don't have previous and next buttons, and you have to create buttons to get your users to these cards. </p>

		
		</div>

	</div> {# /row #}
	
	<div class="row">
		<div class="span10 columns"> <a  href="{% url BuildCard gslug=guide.slug %}"class="btn primary"/>Add a New Card</a></div>
		<div class="span6 columns"><a  href="{% url BuildFloatingCard gslug=guide.slug %}"class="btn primary"/>Add a New Side Card</a></div>
		
	</div> {# /row #}
	
{%else%}
	<div class="row">
		<div class="floating_card_container span16 columns" >

			<div data-bind="template: {name: 'smallCardTemplate',
						  						foreach: VM.floating_cards, templateOptions: { parentList: VM.floating_cards}},
												sortableList: VM.floating_cards" class="connectedSortable ">
			</div>
		</div>
	</div>
	<a  href="{% url BuildFloatingCard gslug=guide.slug %}"class="btn primary"/>Add a New Card</a>
{%endif%}




{%load verbatim_templatetag%} 


{%verbatim%}
	<script id='smallCardTemplate' type='text/html'>
	<div class="smallcardWrapper" id="${id}" data-bind="sortableItem: { item: $data, parentList: $item.parentList }"> 
		<div class="cardNumber"><span data-bind="text: card_number"></span> </div>
		<div class="smallcard">
			<span data-bind="text: title() ? title: 'Untitled Card '"></span>
			{{if thumb }}<br><img src="${thumb}">{{/if}} 
		</div>
		<div class="controls">
			<a href="${edit_url}">Edit</a>
			<a href="${absolute_url}">Preview</a>
			<a href="#" class="delete_link">Delete</a>
			<a href="#" class="delete_link_real" data-bind="click: deleteCard">Sure?</a>
		</div>
	</div>
	</script>
{%endverbatim%}






<br><br><hr><br>
<div class="row " id="options">
	<form action="" method="post" class="column span10 standout offset3" autocomplete="off">
		<h2 class="centext">Guide Details</h2>
		<br>
	{% csrf_token %}
	<div class="clearfix">
        <label for="id_title">Title</label>
        <div class="input">
            <input class="span6" id="id_title" name="title"  type="text" value="{{guide.title}}">
        </div>
     </div>
		<div class="clearfix">
         <label for="id_description">Description</label>
         <div class="input">
           <textarea class="span6" id="id_description" name="description" rows="3">{{guide.description}}</textarea>
         </div>
		 </div>
		
		<div class="clearfix">
	        <label for="id_tags">Tags</label>
	        <div class="input">
	            <input class="span6" id="id_tags" name="tags"  type="text" value="{{guide.tags}}">
	        </div>
	     </div>
	
	
		<div class="clearfix centext">
			<button type="submit" class="btn primary">Save Details </button>
		</div>
		
				<input type="hidden" name="owner" id="id_owner" value="{{user.id}}">
				<div class="hidden">{{form.card_order}}{{form.floating_list}}</div>
	</form>

</div> {# /row standout #}




<br><br><hr><br>
<div class="row standout" id="publish">
	{%if guide.published%}
		{%if guide.private%}
		<div class="column span10 offset3 centext postpub" >
		<h2 class="centext">Secretly Published Guide </h2>
		
			<p>Your guide is secret*, and can be accessed at:<br>
				<a class="big" target="_blank" href="{%url SecretGuideView private_url=guide.private_url%}">guides.ly{%url SecretGuideView private_url=guide.private_url%}</a>
			</p>
			<p> Only share that link with people you want to see it!</p>
			<p class="small centext"><br>* <strong>Relatively</strong> secret, but probably not 100% secure. Please don't store state secrets in your guide. </p>

			<div class="row centext"><br><br><br><button class="btn" data-bind="click: function(){$('#publishOptions').slideDown(); $('.postpub').slideUp(); }"> Change publishing options</button></div>
			
			</div> {# /column #}
			
		{%else%}
		<div class="column span6 offset5 centext postpub">
		
		<h2 class="centext">Published Guide </h2>
		
		<p>Your guide is available at:<br>
			<a class="big" href="{{guide.get_absolute_url}}" target="_blank">guides.ly{{guide.get_absolute_url}}</a></p>
		<p>Consider sharing your guide with these fine services:</p>
		<div class="row">
			<div class="column span1 ">
				<div id="fb-root"></div>
				<script>(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) {return;}
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));</script>
		
				<div class="fb-like center-block" data-href="guides.ly{{guide.get_absolute_url}}" data-send="false" data-layout="button_count" data-width="40" data-show-faces="false"></div>
			</div>
			<div class="column span1 offset1">
				<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
				<a id="twitshare" href="http://twitter.com/share?url= &text=Check out the my guide: {{guide.title}}  guides.ly{{guide.get_absolute_url}}&count=none " class="twitter-share-button">Tweet</a>
			</div>
			<div class="column span1 offset1">
				<g:plusone annotation="none" href="http://guides.ly{{guide.get_absolute_url}}"></g:plusone>
				<script type="text/javascript">
				  (function() {
				    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				    po.src = 'https://apis.google.com/js/plusone.js';
				    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
				  })();
				</script>
				
			</div>	{# / share column #}
			</div> {# /share row #}
			<div class="row centext"><br><br><br><button class="btn" data-bind="click: function(){$('#publishOptions').slideDown(); $('.postpub').slideUp(); }"> Change publishing options</button></div>
						
		</div> {# /column #}
		{%endif%}
		
	{%endif%} {# end if published #}

	<div id="publishOptions" class="column  span14 offset1 {% if guide.published %} hidden {% endif %}" >
	
		<h1 class="centext">Publish  <i>{{guide.title|title}}</i> </h1>
		<h5 class="centext">Guide looking good? Share it with the world.  </h5>
	
		<form action="{%url PublishGuide gslug=guide.slug%}" method="post" class="inputs-list ">
		{% csrf_token %}

			<input type="hidden" name="published" value="True"/> 	

			<p class="centext" data-bind="style: {textDecoration: private_guide() ? 'line-through': 'none'}">Your guide will be publicly available at: <a href="{{guide.get_absolute_url}}" target="_blank">guides.ly{{guide.get_absolute_url}}</a>
		
			<div class="row">
				<div class="column span6">
					<h4>Don't want it public?</h4>
					<p><label class="strong"> <input type="checkbox" name="private" data-bind="checked: private_guide" /> Make it a Private Guide </label></p>
					<p>After you hit publish, we'll give you a secret web address to share with special folks.</p>
				
				</div>
			
				<div class="column span6 offset2">
					<h4>Make something awesome?</h4>
					<p><label class="strong" data-bind="css:{disabled: private_guide}"><input type="checkbox" name="submit_to_cat" checked data-bind="checked: !private_guide(), enable: !private_guide()"/> Showcase it!</label></p>
					<p>We'll check it out, and send you a message when and if we feature it in our showcase.</p>
				</div>
		
			</div>
		

			<br><br>
			{# <p> {{guide.thumb}} This is the image we're using to represent your guide. You can <a href="#">change it</a>.</p> #}

			<div class="row centext">
				<button type="submit" class="btn primary large">Publish it!</button>
			</div>
		</form>
		<br>
	</div> {# /column #}


</div> {# /row #}

<div class="row"><br><br><br><br>
<div class="centext column span6 offset5 standout">Or you can always<br><br>
<a class="btn danger ">Delete This Guide</a>
<br><br> if you really want to.
</div>
</div>


{% endblock %} {# end content #}

templates/create/error.html
{%extends "base.html"%}
{%block content%}
<h1>Error</h1>
{% for key, value in errors.items %}
    {{ key }}: {{ value }}
{% endfor %}

{%endblock%}

templates/create/new_guide.html
{%extends "base.html" %}

{# {%block extrahead%}{%endblock%} #}


{%block header%}
<li> <span class="location">Create A New Guide</a> </li>
{%endblock%}

{%block content%}

<br>
<h1> Your Awesome New Guide</h1>
<br><br>
<div class="row">
	<div class=" column span10  offset3">

		<form action="" method="post">
			{% csrf_token %}
			
			<div class="clearfix">
	            <label for="id_title">Title of Your Guide</label>
	            <div class="input">
	              <input class="span6" id="id_title" name="title"  type="text">
	            </div>
	         </div>
	
			<div class="clearfix">
	            <label for="id_description">A sentence or two  describing it</label>
	            <div class="input">
	              <textarea class="span6" id="id_description" name="textarea2" rows="3"></textarea>
	            </div>
			 </div>
			
			<div class="clearfix">
	            <label> 
					Ordering 
					<a rel="popover" data-content="<b>Ordered:</b> Cards have an order, prev and next buttons. <br><b>Freeform:</b> You must create inputs to let users move through your guide." data-original-title="Ordering?" class="tip">?</a>
				</label>
	            <div class="input">
					<label for="in_lin"> Mostly Ordered <input type="radio" id="in_lin" name="is_linear" value="true" checked="checked" /></label>  
					<label for="in_lin2">Totally Freeform <input type="radio" id="in_lin2" name="is_linear" value=""  /></label>
	            </div>
          </div>
		<br>
		
		<input type="hidden" name="owner" id="id_owner" value="{{user.id}}">
		<div class="hidden">{{form.card_order}}{{form.floating_list}}</div>
		
		<div class="clearfix centext">
			<button type="submit" class="btn primary">Create Guide &amp; Start Building </button>
		</div>
		


		</form>
		
		
	</div> {# /span10 #}
	<div class="span3 columns"></div>
</div> {# /row #}
<br><br><br><br><br><br>	



{%endblock%}